server:
  port: 5555
 
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: stock-Price
        uri: http://localhost:1111/
        predicates:
          - Path=/price/**
      - id: stock-Amount
        uri: http://localhost:2222/
        predicates:
          - Path=/calc/**   
       